# This is a SAM template that represents the architecture of the new serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Basic AWS Lambda function template

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # function config
 
  helloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.helloWorldHandler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 10
      Description: A Lambda function that returns the date and time.
      Policies:
        # Give Lambda basic execution Permission to the helloWorld
        # - AWSLambdaBasicExecutionRole
      Events:
        helloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      
  getIPFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.getIPHandler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 10
      Description: A Lambda function that returns the IP of the visitor.
      Policies:
        # Give Lambda basic execution Permission to the getIP
        # - AWSLambdaBasicExecutionRole
      Events:
        getIP:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ip
            Method: get
          
  getCountryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.getCountryHandler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 10
      Description: A Lambda function that returns the country code of the requestor.
      Policies:
        # Give Lambda basic execution Permission to the getCountry
        # - AWSLambdaBasicExecutionRole
      Events:
        getCountry:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /country
            Method: get
        

  getDeviceInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.getDeviceInfoHandler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 10
      Description: A Lambda function that returns the headers.UserAgent and headers.CloudFront-Is-[deviceList] of the requestor.
      Policies:
        # Give Lambda basic execution Permission to the getDeviceInfo
        # - AWSLambdaBasicExecutionRole
      Events:
        getDeviceInfo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /device
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  helloWorld:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
  getIP:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ip"
  getCountry:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/country"
  getDeviceInfo:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/device"
